export const schedule = [
    { id: 0,
      date: 'Today',
      movie1: 'Alien',
      movie2: 'Hot Rod',
      movie3: 'Home Alone',
      movie4: 'Iron Man',
      movie5: 'Doctor Strange 2',
      movie6: 'LOTR: The Return of the King'
    },
    { id: 1,
      date: 'Tomorrow',
      movie1: 'Home Alone',
      movie2: 'Hot Rod',
      movie3: 'Iron Man',
      movie4: 'Star Wars: Return of the Jedi',
      movie5: 'Doctor Strange 2',
      movie6: 'LOTR: The Return of the King'
    },
    { id: 2,
      date: 'Sep 18th',
      movie1: 'Star Wars: Return of the Jedi',
      movie2: 'Hot Rod',
      movie3: 'Home Alone',
      movie4: 'Iron Man',
      movie5: 'Doctor Strange 2',
      movie6: 'LOTR: The Return of the King'
    },
    { id: 3,
      date: 'Sep 19th',
      movie1: 'Alien',
      movie2: 'Hot Rod',
      movie3: 'Star Wars: Return of the Jedi',
      movie4: 'Iron Man',
      movie5: 'Doctor Strange 2',
      movie6: 'LOTR: The Return of the King'
    },
    { id: 4,
      date: 'Sep 20th',
      movie1: 'Alien',
      movie2: 'Hot Rod',
      movie3: 'Home Alone',
      movie4: 'Star Wars: Return of the Jedi',
      movie5: 'Doctor Strange 2',
      movie6: 'LOTR: The Return of the King'
    },
    { id: 5,
      date: 'Sep 21st',
      movie1: 'Alien',
      movie2: 'Hot Rod',
      movie3: 'Home Alone',
      movie4: 'Iron Man',
      movie5: 'Doctor Strange 2',
      movie6: 'LOTR: The Return of the King'
    },
    { id: 6,
      date: 'Sep 22nd',
      movie1: 'Alien',
      movie2: 'Hot Rod',
      movie3: 'Home Alone',
      movie4: 'Iron Man',
      movie5: 'Doctor Strange 2',
      movie6: 'LOTR: The Return of the King'
    },
    { id: 7,
      date: 'Sep 23rd',
      movie1: 'Alien',
      movie2: 'Hot Rod',
      movie3: 'Home Alone',
      movie4: 'Iron Man',
      movie5: 'Doctor Strange 2',
      movie6: 'LOTR: The Return of the King'
    },
  ]